### ISSUE TITLE
[Bug]: please don't move semantically versioned tags

### ISSUE THREAD

**Issue by yarikk** [l50/goutils#421]
### What happened?

Please don't change semantically versioned tags. Stuff breaks when that happens:
```
verifying github.com/l50/goutils@v1.0.9: checksum mismatch
	downloaded: h1:Mhl0cfP5hzMLro9W+cAKi6pLvNcntNDM9lX21NyarGM=
	go.sum:     h1:h8anV7XQZjov+bKjggt9QfYKFkHmoVPNZ1X8OmjA+cQ=
```
Instead, please consider doing the following: cut a new release, then [retract](https://go.dev/ref/mod#go-mod-file-retract) the broken version in go.mod.

### Any suggestions for fixing this bug?

Workaround for affected users: update to move away from the mutated version. Alternatively, GOPRIVATE or GONOSUMDB may be used by the users to disable checksum checking on specific modules.

From FAQ on https://proxy.golang.org:

> #### I removed a bad release from my repository but it still appears in the mirror, what should I do?

> Whenever possible, the mirror aims to cache content in order to avoid breaking builds for people that depend on your package, so this bad release may still be available in the mirror even if it is not available at the origin. The same situation applies if you delete your entire repository. We suggest creating a new version and encouraging people to use that one instead.

> If you would like to hide versions of a module from the go command, as well as [pkg.go.dev](https://pkg.go.dev/), you should retract them. Retracting a module version involves adding a [retract directive](https://golang.org/ref/mod#go-mod-file-retract) to your go.mod file and publishing a new version. See the Go blog post [New module changes in Go 1.16](https://go.dev/blog/go116-module-changes#module-retraction) and the [modules reference](https://go.dev/ref/mod#go-mod-file-retract) for details.

**Comment by l50** [comment]
@yarikk Thanks for submitting this issue! I'm so sorry about the inconvenience I caused with that previous release. I've been building this repo over the course of many years and there's been some lessons learned along the way :)

I've created release v1.3.1, which adds a retract statement to go.mod for v1.0.9. 

The solution was a bit tricky given we're on v2, but essentially v1.0.9 and v1.1.0 had the same commit, which apparently can cause some issues. I had to point the v1.0.9 tag to another commit, which hopefully won't cause any additional problems with the `retract` in place.

I've also released the latest v2 as well, which I recommend over v1 (which is not actively supported).

Please let me know if the issue has been resolved, or if more needs to be done.

**Comment by l50** [comment]
Haven't heard anything back in a week - considering this issue closed unless specified otherwise.
